### PR TITLE
Added ability to sort returned list from dense_accessors

### PR DESCRIPTION
**Pull request by charest**
The list of matched dense_accessor's is sorted by label lexagraphically.  By default no sorting is performed unless the specialization asks for it.

### CODE REVIEW

**Comment by charest** [comment]
@junghans these are failures due to legion.  I don't think they have anything to do with this pull request.

**Comment by junghans** [comment]
mpi-legion is @ipdemes thing.

**Comment by charest** [comment]
I mean that you should accept this pull request.  It doesn't break anything.

**Comment by ipdemes** [comment]
i don't see how this could break legion, but I will check it out.

**Comment by ipdemes** [comment]
@junghans: an error one get with ctest here related to some cinch/cmake issue, I guess. For example, if you just run ./test/execution/mpi binary by itself - it passes,  if you run it with mpiexec (the way ctest does), it gives you an error like below:

mpiexec has exited due to process rank 0 with PID 6459 on
node f23vm exiting improperly. There are three reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.

This may have caused other processes in the application to be
terminated by signals sent by mpiexec (as reported here).

You can avoid this message by specifying -quiet on the mpiexec command line.

**Comment by ipdemes** [comment]
P.S. I get the same errors when I build previous commit : 01ddb5ce91eff66dda921cf360f8f8c2ba037b64

**Comment by junghans** [comment]
I guess we should just disable these two legion-mpi tests in master.

**Comment by ipdemes** [comment]
Can you just remove "mpiexec" as a default execution command in cmake?

**Comment by ipdemes** [comment]
OK. I'll merge this pull request when all tests are completed

**Pull request merged**
